---
title: "Test Plots"
author: "Cole Sibbald"
date: "Sep. 29, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
data_A <- read.table(file="A-Optimal.txt",header=T)
data_D <- read.table(file="D-Optimal.txt",header=T)
data_E <- read.table(file="E-Optimal.txt",header=T)
```

```{r}
ggplot(data_A,aes(N)) +
  geom_line(aes(y=X2,colour="P=2")) +
  geom_line(aes(y=X3,colour="P=3")) +
  geom_line(aes(y=X4,colour="P=4")) +
  geom_line(aes(y=X5,colour="P=5")) +
  geom_line(aes(y=X6,colour="P=6")) +
  labs(x = "Number of Variables", y = "Copmute Time (s)", title = "A-Optimal (a = -1, b = 1)") + 
  theme(legend.position = c(0.2,0.8)) + 
  scale_color_manual("", values = c("P=2" = "green", "P=3" = "yellow", "P=4" = "Orange", "P=5" = "red", "P=6" = "violet"))

ggplot(data_D,aes(N)) +
  geom_line(aes(y=X2,colour="P=2")) +
  geom_line(aes(y=X3,colour="P=3")) +
  geom_line(aes(y=X4,colour="P=4")) +
  geom_line(aes(y=X5,colour="P=5")) +
  geom_line(aes(y=X6,colour="P=6")) +
  labs(x = "Number of Variables", y = "Compute Time (s)", title = "D-Optimal (a = -1, b = 1)") + 
  theme(legend.position = c(0.2,0.8)) + 
  scale_color_manual("", values = c("P=2" = "green", "P=3" = "yellow", "P=4" = "Orange", "P=5" = "red", "P=6" = "violet"))

ggplot(data_E,aes(N)) +
  geom_line(aes(y=X2,colour="P=2")) +
  geom_line(aes(y=X3,colour="P=3")) +
  geom_line(aes(y=X4,colour="P=4")) +
  geom_line(aes(y=X5,colour="P=5")) +
  geom_line(aes(y=X6,colour="P=6")) +
  labs(x = "Number of Variables", y = "Compute Time (s)", title = "E-Optimal (a = -1, b = 1)") + 
  theme(legend.position = c(0.2,0.8)) + 
  scale_color_manual("", values = c("P=2" = "green", "P=3" = "yellow", "P=4" = "Orange", "P=5" = "red", "P=6" = "violet"))

```


```{r,include=FALSE}
data_A <- read.table(file="A-optimal-output.txt",header=T)
data_D <- read.table(file="D-optimal-output.txt",header=T)

png('A-Optimal-Convergance.png')
ggplot(data_A,aes(N)) +
  geom_line(aes(y=U_i,colour="U_i")) +
  geom_abline(intercept = 0.4575800000000001,slope=0, aes(colour="Asymptote")) +
  labs(x = "Number of Variables", y = "U_i", title = "A-Optimal (a = -1, b = 1)") + 
  ylim(c(0.38,.47)) +
  scale_color_manual("", values = c("U_i" = "green", "Asymptote" = "blue"))
dev.off()

png('D-Optimal-Convergance.png')
ggplot(data_D,aes(N)) +
  geom_line(aes(y=U_i,colour="U_i")) +
  geom_abline(intercept = 0.45248,slope=0, aes(colour="Asymptote")) +
  ylim(c(0.38,.47)) +
  labs(x = "Number of Variables", y = "U_i", title = "D-Optimal (a = -1, b = 1)") + 
  scale_color_manual("", values = c("U_i" = "green", "Asymptote" = "blue"))
dev.off()
```

```{r,include=FALSE}
png('A-Optimal.png')
ggplot(data_A,aes(N)) +
  geom_line(aes(y=X2,colour="P=2")) +
  geom_line(aes(y=X3,colour="P=3")) +
  geom_line(aes(y=X4,colour="P=4")) +
  geom_line(aes(y=X5,colour="P=5")) +
  geom_line(aes(y=X6,colour="P=6")) +
  labs(x = "Number of Variables", y = "Copmute Time (s)", title = "A-Optimal (a = -1, b = 1)") + 
  theme(legend.position = c(0.2,0.8)) + 
  scale_color_manual("", values = c("P=2" = "green", "P=3" = "yellow", "P=4" = "Orange", "P=5" = "red", "P=6" = "violet"))
dev.off()

png('D-Optimal.png')
ggplot(data_D,aes(N)) +
  geom_line(aes(y=X2,colour="P=2")) +
  geom_line(aes(y=X3,colour="P=3")) +
  geom_line(aes(y=X4,colour="P=4")) +
  geom_line(aes(y=X5,colour="P=5")) +
  geom_line(aes(y=X6,colour="P=6")) +
  labs(x = "Number of Variables", y = "Compute Time (s)", title = "D-Optimal (a = -1, b = 1)") + 
  theme(legend.position = c(0.2,0.8)) + 
  scale_color_manual("", values = c("P=2" = "green", "P=3" = "yellow", "P=4" = "Orange", "P=5" = "red", "P=6" = "violet"))
dev.off()

png('E-Optimal.png')
ggplot(data_E,aes(N)) +
  geom_line(aes(y=X2,colour="P=2")) +
  geom_line(aes(y=X3,colour="P=3")) +
  geom_line(aes(y=X4,colour="P=4")) +
  geom_line(aes(y=X5,colour="P=5")) +
  geom_line(aes(y=X6,colour="P=6")) +
  labs(x = "Number of Variables", y = "Compute Time (s)", title = "E-Optimal (a = -1, b = 1)") + 
  theme(legend.position = c(0.2,0.8)) + 
  scale_color_manual("", values = c("P=2" = "green", "P=3" = "yellow", "P=4" = "Orange", "P=5" = "red", "P=6" = "violet"))
dev.off()
```
